language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 1.0.4
branches:
  only:
    - master
before_script:
  - chmod a+x ./scripts/travis-build.sh
  - chmod a+x ./scripts/test.sh
script:
  - ./scripts/travis-build.sh
  - ./scripts/test.sh
notifications:
  email:
    on_success: never
    on_failure: always